### ISSUE TITLE
Unrecognized function or variable 'importONNXFunction'

### ISSUE THREAD

**Issue by orchidas** [georg-goetz/DecayFitNet#2]
Hi Georg,

Thanks a lot for making this available. I am trying to use the toolbox in Matlab. I have installed the DL toolbox and ONNX converter toolbox. However, when I run demo.m, I get this error

Unrecognized function or variable 'importONNXFunction'.

It seems like the only options are importONNXNetwork and importONNXLayers, am I missing something?

P.S - I am using MATLAB R2020a

**Comment by georg-goetz** [comment]
Hi,

The function `importONNXFunction` was unfortunately only introduced in MATLAB 2020b. We have tried using `importONNXNetwork` and/or `importONNXLayers` before, but it seems that they do not support MaxPoolLayers at this point. We haven't really found a good workaround for this yet, apart from requiring MATLAB 2020b or later. Of course, using the Python toolbox would be another alternative.

-Georg
